services:
  kdc:
    build: kdc/
    image: ketzu/krb5
    container_name: kdc
    domainname: example.test
    environment:
      - REALM=EXAMPLE.TEST
      - KDC_PASSWORD=password
      - PRINCIPALS=admin/admin:adminpass,testuser:testpass,service/host:randkey
    volumes:
      - ./data:/data
